<!DOCTYPE HTML>
<html>
  <head>
    <link rel="Stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="Stylesheet" type="text/css" href="/static/css/tango.css">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="alternate" type="application/atom+xml" href="atom.xml" title="Atom feed">
    <title>error - Xu XueHua</title>
    <meta name="keywords" content="Xu XueHua"/>
    <meta name="description" content="Xu XueHua's public notes"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>

  <body>
    <div id="container">
      
<div id="header">
  <div class="post-nav"><a href="/">Home</a>&nbsp;&#187;&nbsp;<a href="/#JavaScript">JavaScript</a>&nbsp;&#187;&nbsp;error
    <span class="updated">Page Updated&nbsp;
      2018-07-10 01:51
    </span></div>
</div>
<div class="clearfix"></div>

<div class="page_title">error</div>

  <div class="toc"><span class="toctitle">Table of Contents</span><ul>
<li><a href="#error">Error 错误处理</a><ul>
<li><a href="#_1">错误分类</a><ul>
<li><a href="#_2">程序逻辑问题</a></li>
<li><a href="#_3">执行过程中的错误</a></li>
</ul>
</li>
<li><a href="#try-catch-finally">try ... catch ... finally</a><ul>
<li><a href="#try-catchfinally">只有try ... catch，没有finally</a></li>
<li><a href="#try-finallycatch">只有try ... finally，没有catch</a></li>
</ul>
</li>
<li><a href="#_4">错误类型</a></li>
<li><a href="#_5">抛出错误</a><ul>
<li><a href="#_6">处理错误</a></li>
</ul>
</li>
<li><a href="#_7">异步错误处理</a></li>
</ul>
</li>
</ul>
</div>
<h1 id="error">Error 错误处理</h1>
<h2 id="_1">错误分类</h2>
<h3 id="_2">程序逻辑问题</h3>
<div class="hlcode"><pre><span class="n">var</span> <span class="n">s</span> <span class="o">=</span> <span class="n">null</span><span class="p">;</span>
<span class="n">var</span> <span class="n">len</span> <span class="o">=</span> <span class="n">s</span><span class="p">.</span><span class="n">length</span><span class="p">;</span> <span class="c1">// TypeError：null变量没有length属性</span>
</pre></div>


<p>对于这种错误，要修复程序</p>
<h3 id="_3">执行过程中的错误</h3>
<p>程序可能遇到无法预测的异常情况而报错，例如，网络连接中断，读取不存在的文件，没有操作权限等。</p>
<p>对于这种错误，我们需要处理它，并可能需要给用户反馈。</p>
<div class="hlcode"><pre><span class="kt">int</span> <span class="n">fd</span> <span class="o">=</span> <span class="n">open</span><span class="p">(</span><span class="s">&quot;/path/to/file&quot;</span><span class="p">,</span> <span class="n">O_RDONLY</span><span class="p">);</span>
<span class="k">if</span> <span class="p">(</span><span class="n">fd</span> <span class="o">==</span> <span class="o">-</span><span class="mi">1</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">printf</span><span class="p">(</span><span class="s">&quot;Error when open file!&quot;</span><span class="p">);</span>
<span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
    <span class="c1">// TODO</span>
<span class="p">}</span>
</pre></div>


<p>通过错误码返回错误，就需要约定什么是正确的返回值，什么是错误的返回值。上面的<code>open()</code>函数约定返回<code>-1</code>表示错误。</p>
<p>显然，这种用错误码表示错误在编写程序时十分不便。</p>
<h2 id="try-catch-finally">try ... catch ... finally</h2>
<div class="hlcode"><pre><span class="err">&#39;</span><span class="n">use</span> <span class="n">strict</span><span class="err">&#39;</span><span class="p">;</span>
<span class="n">var</span> <span class="n">r1</span><span class="p">,</span> <span class="n">r2</span><span class="p">,</span> <span class="n">s</span> <span class="o">=</span> <span class="n">null</span><span class="p">;</span>
<span class="n">try</span> <span class="p">{</span>
    <span class="n">r1</span> <span class="o">=</span> <span class="n">s</span><span class="p">.</span><span class="n">length</span><span class="p">;</span> <span class="c1">// 此处应产生错误</span>
    <span class="n">r2</span> <span class="o">=</span> <span class="mi">100</span><span class="p">;</span> <span class="c1">// 该语句不会执行</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="err">&#39;出错了：&#39;</span> <span class="o">+</span> <span class="n">e</span><span class="p">);</span>
<span class="p">}</span> <span class="n">finally</span> <span class="p">{</span>
    <span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="err">&#39;</span><span class="n">finally</span><span class="err">&#39;</span><span class="p">);</span>
<span class="p">}</span>
<span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="err">&#39;</span><span class="n">r1</span> <span class="o">=</span> <span class="err">&#39;</span> <span class="o">+</span> <span class="n">r1</span><span class="p">);</span> <span class="c1">// r1应为undefined</span>
<span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="err">&#39;</span><span class="n">r2</span> <span class="o">=</span> <span class="err">&#39;</span> <span class="o">+</span> <span class="n">r2</span><span class="p">);</span> <span class="c1">// r2应为undefined</span>
<span class="o">&gt;&gt;&gt;</span>
<span class="err">出错了：</span><span class="n">TypeError</span><span class="o">:</span> <span class="n">Cannot</span> <span class="n">read</span> <span class="n">property</span> <span class="err">&#39;</span><span class="n">length</span><span class="err">&#39;</span> <span class="n">of</span> <span class="n">null</span>
<span class="n">finally</span>
<span class="n">r1</span> <span class="o">=</span> <span class="n">undefined</span>
<span class="n">r2</span> <span class="o">=</span> <span class="n">undefined</span>
</pre></div>


<blockquote>
<p>当代码块被<code>try { ... }</code>包裹的时候，就表示这部分代码执行过程中可能会发生错误，一旦发生错误，就不再继续执行后续代码，转而跳到<code>catch</code>块。<code>catch (e) { ... }</code>包裹的代码就是错误处理代码，变量<code>e</code>表示捕获到的错误。最后，无论有没有错误，<code>finally</code>一定会被执行。</p>
</blockquote>
<p>有错误发生时，执行流程像这样：</p>
<ol>
<li>先执行<code>try { ... }</code>的代码；</li>
<li>执行到出错的语句时，后续语句不再继续执行，转而执行<code>catch (e) { ... }</code>代码；</li>
<li>最后执行<code>finally { ... }</code>代码。</li>
</ol>
<p>而没有错误发生时，执行流程像这样：</p>
<ol>
<li>先执行<code>try { ... }</code>的代码；</li>
<li>因为没有出错，<code>catch (e) { ... }</code>代码不会被执行；</li>
<li>最后执行<code>finally { ... }</code>代码。</li>
</ol>
<p>最后请注意，<code>catch</code>和<code>finally</code>可以不必都出现。</p>
<h3 id="try-catchfinally">只有try ... catch，没有finally</h3>
<div class="hlcode"><pre><span class="n">try</span> <span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span>
</pre></div>


<h3 id="try-finallycatch">只有try ... finally，没有catch</h3>
<div class="hlcode"><pre><span class="n">try</span> <span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span> <span class="n">finally</span> <span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span>
</pre></div>


<h2 id="_4">错误类型</h2>
<p>JavaScript有一个标准的<code>Error</code>对象表示错误，还有从<code>Error</code>派生的<code>TypeError</code>、<code>ReferenceError</code>等错误对象。我们在处理错误时，可以通过<code>catch(e)</code>捕获的变量<code>e</code>访问错误对象：</p>
<div class="hlcode"><pre><span class="n">try</span> <span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">e</span> <span class="n">instanceof</span> <span class="n">TypeError</span><span class="p">)</span> <span class="p">{</span>
        <span class="n">alert</span><span class="p">(</span><span class="err">&#39;</span><span class="n">Type</span> <span class="n">error</span><span class="o">!</span><span class="err">&#39;</span><span class="p">);</span>
    <span class="p">}</span> <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">e</span> <span class="n">instanceof</span> <span class="n">Error</span><span class="p">)</span> <span class="p">{</span>
        <span class="n">alert</span><span class="p">(</span><span class="n">e</span><span class="p">.</span><span class="n">message</span><span class="p">);</span>
    <span class="p">}</span> <span class="k">else</span> <span class="p">{</span>
        <span class="n">alert</span><span class="p">(</span><span class="err">&#39;</span><span class="n">Error</span><span class="o">:</span> <span class="err">&#39;</span> <span class="o">+</span> <span class="n">e</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></div>


<p>使用变量<code>e</code>是一个习惯用法，也可以以其他变量名命名，如<code>catch(ex)</code></p>
<h2 id="_5">抛出错误</h2>
<p>程序也可以主动抛出一个错误，让执行流程直接跳转到<code>catch</code>块。抛出错误使用<code>throw</code>语句</p>
<div class="hlcode"><pre><span class="err">&#39;</span><span class="n">use</span> <span class="n">strict</span><span class="err">&#39;</span><span class="p">;</span>
<span class="n">var</span> <span class="n">r</span><span class="p">,</span> <span class="n">n</span><span class="p">,</span> <span class="n">s</span><span class="p">;</span>
<span class="n">try</span> <span class="p">{</span>
    <span class="n">s</span> <span class="o">=</span> <span class="n">prompt</span><span class="p">(</span><span class="err">&#39;请输入一个数字&#39;</span><span class="p">);</span>
    <span class="n">n</span> <span class="o">=</span> <span class="n">parseInt</span><span class="p">(</span><span class="n">s</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">isNaN</span><span class="p">(</span><span class="n">n</span><span class="p">))</span> <span class="p">{</span>
        <span class="n">throw</span> <span class="n">new</span> <span class="n">Error</span><span class="p">(</span><span class="err">&#39;输入错误&#39;</span><span class="p">);</span>
    <span class="p">}</span>
    <span class="c1">// 计算平方:</span>
    <span class="n">r</span> <span class="o">=</span> <span class="n">n</span> <span class="o">*</span> <span class="n">n</span><span class="p">;</span>
    <span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="n">n</span> <span class="o">+</span> <span class="err">&#39;</span> <span class="o">*</span> <span class="err">&#39;</span> <span class="o">+</span> <span class="n">n</span> <span class="o">+</span> <span class="err">&#39;</span> <span class="o">=</span> <span class="err">&#39;</span> <span class="o">+</span> <span class="n">r</span><span class="p">);</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="err">&#39;出错了：&#39;</span> <span class="o">+</span> <span class="n">e</span><span class="p">);</span>
<span class="p">}</span>
</pre></div>


<h3 id="_6">处理错误</h3>
<p>当我们用catch捕获错误时，一定要编写错误处理语句：</p>
<div class="hlcode"><pre><span class="n">var</span> <span class="n">n</span> <span class="o">=</span> <span class="mi">0</span><span class="p">,</span> <span class="n">s</span><span class="p">;</span>
<span class="n">try</span> <span class="p">{</span>
    <span class="n">n</span> <span class="o">=</span> <span class="n">s</span><span class="p">.</span><span class="n">length</span><span class="p">;</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="n">e</span><span class="p">);</span>
<span class="p">}</span>
<span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="n">n</span><span class="p">);</span>
</pre></div>


<p>哪怕仅仅把错误打印出来，也不要什么也不干：</p>
<div class="hlcode"><pre><span class="n">var</span> <span class="n">n</span> <span class="o">=</span> <span class="mi">0</span><span class="p">,</span> <span class="n">s</span><span class="p">;</span>
<span class="n">try</span> <span class="p">{</span>
    <span class="n">n</span> <span class="o">=</span> <span class="n">s</span><span class="p">.</span><span class="n">length</span><span class="p">;</span>
<span class="p">}</span> <span class="n">catch</span> <span class="p">(</span><span class="n">e</span><span class="p">)</span> <span class="p">{</span>
<span class="p">}</span>
<span class="n">console</span><span class="p">.</span><span class="n">log</span><span class="p">(</span><span class="n">n</span><span class="p">);</span>
</pre></div>


<p>因为catch到错误却什么都不执行，就不知道程序执行过程中到底有没有发生错误。</p>
<p>处理错误时，请不要简单粗暴地用<code>alert()</code>把错误显示给用户。</p>
<h2 id="_7">异步错误处理</h2>
<p>编写JavaScript代码时，我们要时刻牢记，JavaScript引擎是一个事件驱动的执行引擎，代码总是以单线程执行，而回调函数的执行需要等到下一个满足条件的事件出现后，才会被执行。</p>
<p>例如，<code>setTimeout()</code>函数可以传入回调函数，并在指定若干毫秒后执行：</p>
<div class="hlcode"><pre><span class="kd">function</span> <span class="nx">printTime</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s1">&#39;It is time!&#39;</span><span class="p">);</span>
<span class="p">}</span>

<span class="nx">setTimeout</span><span class="p">(</span><span class="nx">printTime</span><span class="p">,</span> <span class="mi">1000</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s1">&#39;done&#39;</span><span class="p">);</span>
</pre></div>


<p>上面的代码会先打印<code>done</code>，1秒后才会打印<code>It is time!</code>。</p>
<p>如果<code>printTime()</code>函数内部发生了错误，我们试图用try包裹<code>setTimeout()</code>是无效的：</p>
<div class="hlcode"><pre><span class="s1">&#39;use strict&#39;</span><span class="p">;</span>
<span class="kd">function</span> <span class="nx">printTime</span><span class="p">()</span> <span class="p">{</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">();</span>
<span class="p">}</span>

<span class="k">try</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(</span><span class="nx">printTime</span><span class="p">,</span> <span class="mi">1000</span><span class="p">);</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s1">&#39;done&#39;</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">);</span>
<span class="p">}</span>
<span class="o">&gt;&gt;&gt;</span>
<span class="nx">done</span>
</pre></div>
    </div>
    <div id="footer">
      <span>
        <p>Copyright © 2018 Xu XueHua.
        Powered by <a href="http://simiki.org/" target="_blank">Simiki</a>.</p>
        <p>Site Generated 2018-07-12 15:05:29</p>
      </span>
    </div>

    
    
  </body>
</html>